// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyWorkbookChanges() {
  return window['go']['wails']['DesktopApp']['ApplyWorkbookChanges']();
}

export function GetStatusSummary() {
  return window['go']['wails']['DesktopApp']['GetStatusSummary']();
}

export function InitializeWorkspace(arg1, arg2) {
  return window['go']['wails']['DesktopApp']['InitializeWorkspace'](arg1, arg2);
}

export function OpenWorkbook(arg1) {
  return window['go']['wails']['DesktopApp']['OpenWorkbook'](arg1);
}

export function RefreshNow() {
  return window['go']['wails']['DesktopApp']['RefreshNow']();
}

export function SelectExistingWorkbookPath(arg1) {
  return window['go']['wails']['DesktopApp']['SelectExistingWorkbookPath'](arg1);
}

export function SelectRootDirectory(arg1) {
  return window['go']['wails']['DesktopApp']['SelectRootDirectory'](arg1);
}

export function SelectWorkbookSavePath(arg1) {
  return window['go']['wails']['DesktopApp']['SelectWorkbookSavePath'](arg1);
}

export function StartWatching() {
  return window['go']['wails']['DesktopApp']['StartWatching']();
}

export function StopWatching() {
  return window['go']['wails']['DesktopApp']['StopWatching']();
}
