// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function ApplyWorkbookChanges():Promise<app.StatusSummary>;

export function GetStatusSummary():Promise<app.StatusSummary>;

export function InitializeWorkspace(arg1:string,arg2:string):Promise<app.StatusSummary>;

export function OpenWorkbook(arg1:string):Promise<void>;

export function RefreshNow():Promise<app.StatusSummary>;

export function SelectExistingWorkbookPath(arg1:string):Promise<string>;

export function SelectRootDirectory(arg1:string):Promise<string>;

export function SelectWorkbookSavePath(arg1:string):Promise<string>;

export function StartWatching():Promise<app.StatusSummary>;

export function StopWatching():Promise<app.StatusSummary>;
